name: ItemsAdderBetterCommands
version: '${version}'
main: toutouchien.itemsadderbettercommands.ItemsAdderBetterCommands
api-version: '${minecraftVersion}'
load: STARTUP
authors: [ Toutouchien ]

dependencies:
  server:
    ItemsAdder:
      load: BEFORE
      required: false